# Generated by Django 6.0.7 on 2026-07-12 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingzProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_low', models.CharField(blank=True, default='', max_length=4)),
                ('detected_high', models.CharField(blank=True, default='', max_length=4)),
                ('goal_low', models.CharField(blank=True, default='', max_length=4)),
                ('goal_high', models.CharField(blank=True, default='', max_length=4)),
                ('safe_low', models.CharField(blank=True, default='', max_length=4)),
                ('safe_high', models.CharField(blank=True, default='', max_length=4)),
                ('fatigue_risk', models.PositiveSmallIntegerField(default=0)),
                ('cooldown_compliance', models.PositiveSmallIntegerField(default=100)),
                ('boss_unlocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='singz_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
