# Generated by Django 5.2.15 on 2026-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_energy_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='spinaz',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('statz', 'StatZ')], default='free', max_length=10),
        ),
    ]
