# Generated by Django 6.0.7 on 2026-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birthday_profile_personas_profile_spinaz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_refill',
            field=models.DateField(blank=True, null=True),
        ),
    ]
