# Generated by Django 5.2.15 on 2026-07-11 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('friends', 'Friends'), ('fans', 'Fans'), ('partners', 'Partners'), ('blocked', 'Blocked'), ('custom', 'Custom')], max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='in_groupz', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'title'),
            },
        ),
    ]
