# Generated by Django 5.2.16 on 2026-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messagez", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="body",
            field=models.TextField(),
        ),
    ]
