# Generated by Django 5.2.16 on 2026-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collabz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collabinterest",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
