# Generated by Django 5.2.16 on 2026-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specentry",
            name="label",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="specentry",
            name="value",
            field=models.TextField(),
        ),
    ]
