# Generated by Django 6.0.7 on 2026-07-12 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapzProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_styles', models.JSONField(blank=True, default=list)),
                ('bpm_min', models.PositiveSmallIntegerField(default=70)),
                ('bpm_max', models.PositiveSmallIntegerField(default=95)),
                ('style_mastery', models.JSONField(blank=True, default=dict)),
                ('delivery_confidence', models.PositiveSmallIntegerField(default=0)),
                ('breath_control', models.PositiveSmallIntegerField(default=0)),
                ('writing_confidence', models.PositiveSmallIntegerField(default=0)),
                ('boss_unlocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapz_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
