import { lazy, Suspense, useCallback, useEffect, useRef, useState } from "react";
import { api } from "./api.js";
import { asList } from "./shape.js";
import { Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { Loader2, LogOut, ChevronLeft, ChevronRight, Volume2, VolumeX } from "lucide-react";
import { isSoundOn, playSoundPreview, setSoundOn } from "./sound.js";
import { openable } from "./openable.js";
import { useAuth } from "./auth/AuthContext.jsx";
import AdFrame from "./AdFrame.jsx";
import Dock, { usePickConnectZ } from "./PickConnectZ.jsx";
import ErrorBoundary from "./ErrorBoundary.jsx";
import Tour from "./Tour.jsx";
import { SPINAZ } from "./resources.js";

// Every screen below used to be a static import, which means a cold visitor
// hitting the logged-out Landing page paid for the ENTIRE authenticated app —
// all ~28 tabs, SingZ through BugZ — before a single pixel of "here's what
// this is" painted. That's the 730KB single chunk Vite's own build output
// warns about. lazy() + Suspense (below) means each route/tab downloads only
// when it's actually opened, so the cold path (Landing → /try → Register) now
// ships close to nothing extra. JSX referencing a lazy component (as TABS
// does, below) does NOT trigger its import — only mounting it does, which is
// why TABS can stay exactly as written.
import { lazyRoute } from "./chunkError.js";

const Login = lazy(lazyRoute(() => import("./auth/Login.jsx")));
const Register = lazy(lazyRoute(() => import("./auth/Register.jsx")));
const ForgotPassword = lazy(lazyRoute(() => import("./auth/ForgotPassword.jsx")));
const ResetPassword = lazy(lazyRoute(() => import("./auth/ResetPassword.jsx")));
const MimeZ = lazy(lazyRoute(() => import("./apps/MimeZ.jsx")));
const DirectZ = lazy(lazyRoute(() => import("./apps/DirectZ.jsx")));
const LessonZ = lazy(lazyRoute(() => import("./apps/LessonZ.jsx")));
const InstrumentZ = lazy(lazyRoute(() => import("./apps/InstrumentZ.jsx")));
const MessageZ = lazy(lazyRoute(() => import("./apps/MessageZ.jsx")));
const ProfileZ = lazy(lazyRoute(() => import("./apps/ProfileZ.jsx")));
const GroupZ = lazy(lazyRoute(() => import("./apps/GroupZ.jsx")));
const CollabZ = lazy(lazyRoute(() => import("./apps/CollabZ.jsx")));
const BattleZ = lazy(lazyRoute(() => import("./apps/BattleZ.jsx")));
const LabelZ = lazy(lazyRoute(() => import("./apps/LabelZ.jsx")));
const BugZ = lazy(lazyRoute(() => import("./apps/BugZ.jsx")));
const PostZ = lazy(lazyRoute(() => import("./apps/PostZ.jsx")));
const KeyConnectZ = lazy(lazyRoute(() => import("./apps/KeyConnectZ.jsx")));
const OCC = lazy(lazyRoute(() => import("./apps/OCC.jsx")));
const SocialConnectZ = lazy(lazyRoute(() => import("./apps/SocialConnectZ.jsx")));
const SpecZ = lazy(lazyRoute(() => import("./apps/SpecZ.jsx")));
const MembershipZ = lazy(lazyRoute(() => import("./apps/MembershipZ.jsx")));
const AdZ = lazy(lazyRoute(() => import("./apps/AdZ.jsx")));
const OfferZ = lazy(lazyRoute(() => import("./apps/OfferZ.jsx")));
const OnboardZ = lazy(lazyRoute(() => import("./apps/OnboardZ.jsx")));
const PublicPost = lazy(lazyRoute(() => import("./apps/PublicPost.jsx")));
const PublicProfile = lazy(lazyRoute(() => import("./apps/PublicProfile.jsx")));
const TrialTake = lazy(lazyRoute(() => import("./apps/TrialTake.jsx")));
const PublicPlaylist = lazy(lazyRoute(() => import("./apps/PublicPlaylist.jsx")));
const PlaylistZ = lazy(lazyRoute(() => import("./apps/PlaylistZ.jsx")));
const MemberProfile = lazy(lazyRoute(() => import("./apps/MemberProfile.jsx")));
const LogZ = lazy(lazyRoute(() => import("./apps/LogZ.jsx")));
const RoyaltieZ = lazy(lazyRoute(() => import("./apps/RoyaltieZ.jsx")));
const CallZ = lazy(lazyRoute(() => import("./apps/CallZ.jsx")));
const GameZ = lazy(lazyRoute(() => import("./apps/GameZ.jsx")));
const SoundZ = lazy(lazyRoute(() => import("./apps/SoundZ.jsx")));
const FunnelZ = lazy(lazyRoute(() => import("./apps/FunnelZ.jsx")));
const HabitZ = lazy(lazyRoute(() => import("./apps/HabitZ.jsx")));
const JournalZ = lazy(lazyRoute(() => import("./apps/JournalZ.jsx")));
const Landing = lazy(lazyRoute(() => import("./Landing.jsx")));

// A minimal, theme-matched fallback — Suspense shows this for the split
// second a chunk is in flight. Same spinner RequireAuth already used, so a
// lazy chunk loading doesn't look like a different kind of wait.
function RouteFallback() {
  return (
    <div className="flex min-h-screen items-center justify-center text-white/50">
      <Loader2 className="mr-2 animate-spin" size={18} /> Loading…
    </div>
  );
}

// CUSTOM_ICONS registry — keyed to EXACT filenames (platform convention).
// Complete platform set from Corey's icon inventory (Jul 6). Missing files
// fall back to the MCZ logo via <IconImg> until dropped into /public/icons/.
// ICON ARTWORK: Corey's own PNGs, not the generated neon set.
//
// The `-neon.svg` icons were generated by `tools/make-neon-icons.mjs` and they
// are vector, so they scale — but they are simple line glyphs against real
// designed artwork, and next to the actual icon set they read as low-detail.
// The registry points at the artwork.
//
// Three keys still hold a neon SVG, each for its own reason:
//
//   * postz.png   — kept deliberately. It is the one Corey asked for and liked.
//   * journalz.png— the artwork exists on Corey's machine and has never been
//                   committed. Pointing at a file that is not in the repo does
//                   not error, it silently falls back to the MCZ logo, so this
//                   stays on the SVG until the PNG lands.
//   * funnelz.png — no artwork was ever drawn; FunnelZ is owner-only.
//
// The generator stays in `tools/` — it is what made the three above, and it is
// how a new tab gets a placeholder before there is art for it.
export const CUSTOM_ICONS = {
  "arsenal.png": "/icons/arsenal.png",
  "azrael.png": "/icons/azrael.png",
  "background.png": "/icons/background.png",
  "battlez.png": "/icons/battlez.png",
  "boardz.png": "/icons/boardz.png",
  "bodiez.png": "/icons/bodiez.png",
  "bugz.png": "/icons/bugz.png",
  "callz.png": "/icons/callz.png",
  "callz_ai.png": "/icons/callz_ai.png",
  "callz_ai.webp": "/icons/callz_ai.webp",
  "callz_user.png": "/icons/callz_user.png",
  "callz_user.webp": "/icons/callz_user.webp",
  "cleanconnectz.png": "/icons/cleanconnectz.png",
  "collabz.png": "/icons/collabz.png",
  "collabz_originalz.png": "/icons/collabz_originalz.png",
  "collabz_remixez.png": "/icons/collabz_remixez.png",
  "coverz.png": "/icons/coverz.png",
  "crewz.png": "/icons/crewz.png",
  "dawz.png": "/icons/dawz.png",
  "dawz_formulawon.png": "/icons/dawz_formulawon.png",
  "designz.png": "/icons/designz.png",
  "developz.png": "/icons/developz.png",
  "instrumentz.png": "/icons/instrumentz.png",
  "drumz.png": "/icons/drumz.png",
  "violinz.png": "/icons/violinz.png",
  "guitarz.png": "/icons/guitarz.png",
  "bassz.png": "/icons/bassz.png",
  "keyz.png": "/icons/keyz.png",
  "directz.png": "/icons/directz.png",
  "distributez.png": "/icons/distributez.png",
  "energy.png": "/icons/energy.png",
  "facez.png": "/icons/facez.png",
  "favicon.webp": "/favicon.webp",
  "fruity_mobius.png": "/icons/fruity_mobius.png",
  "groupz.png": "/icons/groupz.png",
  "groupz_blocked.png": "/icons/groupz_blocked.png",
  "groupz_custom.png": "/icons/groupz_custom.png",
  "groupz_fanz.png": "/icons/groupz_fanz.png",
  "groupz_friendz.png": "/icons/groupz_friendz.png",
  "homez.png": "/icons/homez.png",
  "imagez.png": "/icons/imagez.png",
  "inbox.png": "/icons/inbox.png",
  "inbox_alt.png": "/icons/inbox_alt.png",
  "intelligence.png": "/icons/intelligence.png",
  "intuition.png": "/icons/intuition.png",
  "keyconnectz.png": "/icons/keyconnectz.png",
  "labelz.png": "/icons/labelz.png",
  "lessonz.png": "/icons/lessonz.png",
  "lilith_anytime.png": "/icons/lilith_anytime.png",
  "lilith_logbook.png": "/icons/lilith_logbook.png",
  "lilith_today.png": "/icons/lilith_today.png",
  "lilith_today2.png": "/icons/lilith_today2.png",
  "lilith_trash.png": "/icons/lilith_trash.png",
  "lilith_upcoming.png": "/icons/lilith_upcoming.png",
  "logo.png": "/mcz-logo-v5.jpg",
  "managez.png": "/icons/managez.png",
  "messagez.png": "/icons/messagez.png",
  "messagez_outbox.png": "/icons/messagez_outbox.png",
  "mimez.png": "/icons/mimez.png",
  "mixez.png": "/icons/mixez.png",
  "occ.png": "/icons/occ.png",
  "offerz.png": "/icons/offerz.png",
  "adz.png": "/icons/adz.png",
  "money.png": "/icons/money.png",
  // New editions — neon signage dropped in Jul 16.
  "specz.png": "/icons/specz.png",
  "nationalitiez.png": "/icons/nationalitiez.png",
  "onboardz.png": "/icons/onboardz.png",
  // Neon rebuild of the cream/teal PostZ mark. The key stays the .png the
  // rest of the platform refers to and the value points at the SVG — the
  // same indirection "logo.png" → the .jpg already uses, and the reason this
  // registry maps names to paths instead of just globbing a folder.
  "postz.png": "/icons/postz-neon.svg",
  "personaz.png": "/icons/personaz.png",
  "personaz_arscout.png": "/icons/personaz_arscout.png",
  "personaz_designer.png": "/icons/personaz_designer.png",
  // Manga-styled alternate art for the Designer PersonaZ — a Premium ICON only.
  // The PersonaZ itself is free to anyone; this is the cosmetic upgrade.
  "personaz_designer_manga.png": "/icons/personaz_designer_manga.png",
  "personaz_developer.png": "/icons/personaz_developer.png",
  "personaz_director.png": "/icons/personaz_director.png",
  "personaz_director.webp": "/icons/personaz_director.webp",
  "personaz_ghostwriter.png": "/icons/personaz_ghostwriter.png",
  "personaz_indieartist.png": "/icons/personaz_indieartist.png",
  "personaz_manager.png": "/icons/personaz_manager.png",
  "personaz_mime.png": "/icons/personaz_mime.png",
  "personaz_mixengineer.png": "/icons/personaz_mixengineer.png",
  "personaz_producer.png": "/icons/personaz_producer.png",
  "personaz_videographer.png": "/icons/personaz_videographer.png",
  "pickconz.png": "/icons/pickconz.png",
  "preferencez.png": "/icons/preferencez.png",
  "producez.png": "/icons/producez.png",
  "rapz.png": "/icons/rapz.png",
  "ratez.png": "/icons/ratez.png",
  "royaltiez.png": "/icons/royaltiez.png",
  "scoutz.png": "/icons/scoutz.png",
  "sentencez.png": "/icons/sentencez.png",
  "shotz.png": "/icons/shotz.png",
  "singz.png": "/icons/singz.png",
  "skillz.png": "/icons/skillz.png",
  "social_connectz.png": "/icons/social_connectz.png",
  "socialz.png": "/icons/socialz.png",
  "sonday.png": "/icons/sonday.png",
  "playlistz.png": "/icons/playlistz.png",
  "spinaz.png": "/icons/spinaz.png",
  "substancez.png": "/icons/substancez.png",
  "toolz_lilith.png": "/icons/toolz_lilith.png",
  "trump_toupee.png": "/icons/trump_toupee.png",
  "venuez.png": "/icons/venuez.png",
  "venuez_alt.png": "/icons/venuez_alt.png",
  "vis_group.png": "/icons/vis_group.png",
  "vis_private.png": "/icons/vis_private.png",
  "vis_public.png": "/icons/vis_public.png",
  "vis_restricted.png": "/icons/vis_restricted.png",
  "witchcraft.png": "/icons/witchcraft.png",
  "writez.png": "/icons/writez.png",
  // Live surfaces whose art was on disk but never registered — so they were
  // silently falling back to the MCZ logo on their own tab. WorkZ is new art.
  "workz.png": "/icons/workz.png",
  "habitz.png": "/icons/habitz.png",
  "journalz.png": "/icons/journalz-neon.svg",
  "logz.png": "/icons/logz.png",
  // Registered ahead of the MCZ2 surface being wired up, so its rows don't
  // land as logos the day it is.
  "analytics.png": "/icons/analytics.png",
  "builder.png": "/icons/builder.png",
  "filez.png": "/icons/filez.png",
  "gamez.png": "/icons/gamez.png",
  // No artwork for SoundZ — it is a tab this session added, so it takes a
  // generated neon icon like FunnelZ does until there is a drawing for it.
  "soundz.png": "/icons/soundz-neon.svg",
  "gitz.png": "/icons/gitz.png",
  "pathz.png": "/icons/pathz.png",
  "imageconnectz.png": "/icons/imageconnectz.png",
  "instrumentalconnectz.png": "/icons/instrumentalconnectz.png",
  "languagez.png": "/icons/languagez.png",
  "languagez_pt.png": "/icons/languagez_pt.png",
  "membership.png": "/icons/membership.png",
  "merchz.png": "/icons/merchz.png",
  "moodz.png": "/icons/moodz.png",
  "onboardz.jpg": "/icons/onboardz.jpg",
  "parcel.png": "/icons/parcel.png",
  "personaz_weightlifter.png": "/icons/personaz_weightlifter.png",
  "preferencez_partner.jpg": "/icons/preferencez_partner.jpg",
  "sentencez_editor.png": "/icons/sentencez_editor.png",
  "tellz.png": "/icons/tellz.png",
  "tier_premium.png": "/icons/tier_premium.png",
  "tier_statz.png": "/icons/tier_statz.png",
  "videoz.png": "/icons/videoz.png",
  "zodiacz.png": "/icons/zodiacz.png",
  // BadgeZ artwork — each badge that has real art names it; the rest carry
  // their emoji. Registered so the fallback is the emoji, not a logo.
  "badge_owner.png": "/icons/badge_owner.png",
  "badge_founding.png": "/icons/badge_founding.png",
  "badge_gifted.png": "/icons/badge_gifted.png",
  "badge_sexy.png": "/icons/badge_sexy.png",
  "badge_polyglot.png": "/icons/badge_polyglot.png",
  "badge_patron.png": "/icons/badge_patron.png",
  "badgez.png": "/icons/badgez.png",
  // Reserved ahead of the artwork. These eight OCC tabs are on their emoji
  // until the art exists; the keys are registered now so dropping the file
  // into public/icons/ is the whole job — nothing here has to change. Missing
  // files fall back to the tab's emoji, not to the logo (see IconImg).
  "editor.png": "/icons/editor.png",
  "taskz.png": "/icons/taskz.png",
  "codez.png": "/icons/codez.png",
  "mistakez.png": "/icons/mistakez.png",
  "characterz.png": "/icons/characterz.png",
  "console.png": "/icons/console.png",
  "search.png": "/icons/search.png",
  "welcome.png": "/icons/welcome.png",
  // Owner-only tab — reserved ahead of the artwork, same as the rest above;
  // falls back to the MCZ logo until a file lands at /public/icons/funnelz.png.
  "funnelz.png": "/icons/funnelz-neon.svg",
};

// Renders a registry icon; if the file is missing (still being remade),
// falls back to the MCZ logo instead of a broken image.
export function IconImg({ icon, alt = "", className = "", fallback = null }) {
  // A key can be registered before its artwork lands — that is deliberate, so
  // dropping the file into public/icons/ is the only step needed to light it
  // up. Until it does, the file 404s, and `fallback` is what the caller wants
  // shown instead of the MCZ logo (OCC passes the tab's emoji, which still
  // means the right thing where a generic logo would mean nothing).
  const [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [icon]);
  if (failed && fallback !== null) return fallback;
  return (
    <img
      src={CUSTOM_ICONS[icon] || "/mcz-logo-v4.png"}
      alt={alt}
      className={className}
      onError={(e) => {
        if (fallback !== null) {
          setFailed(true);
          return;
        }
        if (!e.currentTarget.dataset.fbk) {
          e.currentTarget.dataset.fbk = "1";
          e.currentTarget.src = "/mcz-logo-v4.png";
        }
      }}
    />
  );
}

// LogicZ: every tab has its own address, named after the tab with the trailing
// Z dropped — /post, /battle, /sing. Derived from the key, never typed, because
// a hand-written address is one that drifts from the tab it names.
//
// Until this existed the whole app lived at "/" and switched tabs through a
// custom event: no tab could be linked, bookmarked, or reached with the back
// button. A screen with no address is one you can only tell somebody how to find.
export const slugFor = (key) =>
  key.endsWith("z") && key.length > 2 ? key.slice(0, -1) : key;
export const tabForSlug = (slug) =>
  TABS.find((t) => slugFor(t.key) === String(slug || "").toLowerCase());

const TABS = [
  { key: "onboardz", label: "OnboardZ", icon: "onboardz.png", el: <OnboardZ /> },
  { key: "postz", label: "PostZ", icon: "postz.png", el: <PostZ /> },
  { key: "playlistz", label: "PlaylistZ", icon: "playlistz.png", el: <PlaylistZ /> },
  { key: "social", label: "Social ConnectZ", icon: "social_connectz.png", el: <SocialConnectZ /> },
  { key: "profilez", label: "ProfileZ", icon: "personaz.png", el: <ProfileZ /> },
  { key: "specz", label: "SpecZ", icon: "specz.png", el: <SpecZ /> },
  { key: "membershipz", label: "MembershipZ", icon: "money.png", el: <MembershipZ /> },
  { key: "adz", label: "AdZ", icon: "adz.png", el: <AdZ /> },
  { key: "offerz", label: "OfferZ", icon: "offerz.png", el: <OfferZ /> },
  { key: "mimez", label: "MimeZ", icon: "mimez.png", el: <MimeZ /> },
  { key: "directz", label: "DirectZ", icon: "directz.png", el: <DirectZ /> },
  { key: "lessonz", label: "LessonZ", icon: "lessonz.png", el: <LessonZ /> },
  { key: "singz", label: "SingZ", icon: "singz.png",
    el: <InstrumentZ appKey="singz" icon="singz.png" title="SingZ" accent="#f472b6"
        tagline="Vocal training game — range detection, quests, Boss SongZ, voice health first." /> },
  { key: "rapz", label: "RapZ", icon: "rapz.png",
    el: <InstrumentZ appKey="rapz" icon="rapz.png" title="RapZ" accent="#f59e0b"
        tagline="Rap training — 16 style tracks, breath control, combo meter, Boss Mode." /> },
  { key: "messagez", label: "MessageZ", icon: "messagez.png", el: <MessageZ /> },
  { key: "keyconnectz", label: "KeyConnectZ", icon: "keyconnectz.png", el: <KeyConnectZ /> },
  { key: "occ", label: "OCC", icon: "occ.png", el: <OCC /> },
  { key: "logz", label: "LogZ", icon: "logz.png", el: <LogZ /> },
  { key: "royaltiez", label: "RoyaltieZ", icon: "royaltiez.png", el: <RoyaltieZ /> },
  { key: "callz", label: "CallZ", icon: "callz.png", el: <CallZ /> },
  { key: "gamez", label: "GameZ", icon: "gamez.png", el: <GameZ /> },
  { key: "soundz", label: "SoundZ", icon: "soundz.png", el: <SoundZ /> },
  { key: "journalz", label: "JournalZ", icon: "journalz.png", el: <JournalZ /> },
  { key: "habitz", label: "HabitZ", icon: "habitz.png", el: <HabitZ /> },
  { key: "collabz", label: "CollabZ", icon: "collabz.png", el: <CollabZ /> },
  { key: "battlez", label: "BattleZ", icon: "battlez.png", el: <BattleZ /> },
  { key: "labelz", label: "LabelZ", icon: "labelz.png", el: <LabelZ /> },
  { key: "groupz", label: "GroupZ", icon: "groupz.png", el: <GroupZ /> },
  { key: "bugz", label: "BugZ", icon: "bugz.png", el: <BugZ /> },
  // Owner-only — filtered out of the Dock for everyone else in Home(),
  // below. The route and TABS entry still exist for anyone who is the
  // owner and lands here directly (e.g. a bookmark), and FunnelZ itself
  // shows nothing to a non-owner even if they reach it another way.
  { key: "funnelz", label: "FunnelZ", icon: "funnelz.png", el: <FunnelZ /> },
];

function RequireAuth({ children }) {
  const { user, loading } = useAuth();
  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center text-white/50">
        <Loader2 className="mr-2 animate-spin" size={18} /> Loading…
      </div>
    );
  }
  return user ? children : <Navigate to="/login" replace />;
}

// "/" is the one URL that gets shared, indexed and clicked cold — the
// index.html SEO meta and every OG card point at it. A signed-in member
// should land in the app; anyone else gets the marketing page that makes
// good on what those links promised, not a bare "Welcome back" login form
// (that redirect is still what every OTHER protected route does — a deep
// link like /battle while logged out is someone who already knows what this
// is, and /login is the right place to send them).
function RootRoute() {
  const { user, loading } = useAuth();
  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center text-white/50">
        <Loader2 className="mr-2 animate-spin" size={18} /> Loading…
      </div>
    );
  }
  return user ? <Home /> : <Landing />;
}

// SoundZ on/off. It lives in the header rather than buried in a settings
// screen because it is the control somebody reaches for the moment a sound
// surprises them — a mute you have to go hunting for is one you resent.
// Flipping it ON plays the coin, so you hear what you just agreed to; the
// click is also the user gesture browsers require before any audio at all.
function SoundToggle() {
  const [on, setOn] = useState(isSoundOn);
  useEffect(() => {
    const h = (e) => setOn(!!e.detail);
    window.addEventListener("mcz-sound-changed", h);
    return () => window.removeEventListener("mcz-sound-changed", h);
  }, []);
  return (
    <button
      onClick={() => {
        const next = !on;
        setSoundOn(next);
        setOn(next);
        if (next) playSoundPreview();
      }}
      className={`rounded-lg p-1.5 transition hover:bg-white/10 ${
        on ? "text-mcz-cyan" : "text-white/40"}`}
      title={on ? "SoundZ on — resource changes make a sound" : "SoundZ off — turn sounds on"}
      aria-pressed={on}
    >
      {on ? <Volume2 size={16} /> : <VolumeX size={16} />}
    </button>
  );
}

function CommunityBar({ onOpenMember }) {
  const [stats, setStats] = useState(null);
  useEffect(() => {
    let on = true;
    const load = () => api("/api/auth/stats/").then((s) => on && setStats(s)).catch(() => {});
    load();
    const t = setInterval(load, 60000); // refresh every minute
    return () => { on = false; clearInterval(t); };
  }, []);
  if (!stats) return null;
  return (
    <div className="neon-frame mb-6 space-y-2 p-4">
      <div className="flex flex-wrap items-center gap-3 text-sm">
        <span className="pill">👥 {stats.total_members} members</span>
        <span className="pill !border-emerald-400/40 !text-emerald-300">
          <span className="mr-1 inline-block h-2 w-2 animate-pulse rounded-full bg-emerald-400" />
          {stats.online_now} online now
        </span>
        <span className="pill !text-mcz-gold">⚡ {stats.my_energy} Energy</span>
        <span className="pill !text-mcz-pink">{SPINAZ} {stats.my_spinaz} SpinaZ</span>
        {stats.my_promptz_daily != null && (
          <span className="pill !text-mcz-cyan"
                title={`Free AI prompts today (free 1 · premium 5 · statZ 10) — reset daily, don't stack.${stats.my_promptz ? ` Plus ${stats.my_promptz} prepaid PromptZ.` : ""}`}>
            🏷️ {stats.my_promptz_daily_remaining}/{stats.my_promptz_daily} prompts
          </span>
        )}
        <span className="pill uppercase !text-mcz-cyan">{stats.my_tier}</span>
        {stats.my_zodiac && <span className="pill">{stats.my_zodiac}</span>}
      </div>
      {stats.online_members?.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {(stats.online_members || []).map((u) => (
            <button
              key={u}
              onClick={() => onOpenMember?.(u)}
              title={`View ${u}'s profile`}
              className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1 text-xs text-emerald-200 transition hover:border-emerald-400/60 hover:bg-emerald-400/20 hover:shadow-neon active:scale-95"
            >
              ● {u}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// Post-login shell — modeled on the Music ConnectZ vA2.3 reference HTML:
// sticky gradient header (logo · title/date · balance · profile), a horizontal
// scrollable tab bar, and a card-style content area. Rebuilt in the neon MCZ
// theme with the new rainbow logo and the PostZ / Social ConnectZ / SpecZ /
// NationalitieZ editions from the synthesized blueprints.
// Corey-voice tab descriptions (blueprint Global Rule: "clicking the tab icon
// opens a modal showing the Corey voice description with emoji").
const TAB_ABOUT = {
  onboardz: "👋 OnboardZ — your guided first session. Set up your ProfileZ, drop your first PostZ, rate a few tracks, and refer a friend for 300 SpinaZ.",
  postz: "🎵 Drop your work as a PostZ. After 30s the community can rate it 1–10 (anyone but you); after 60s they can comment. Every rating you give earns +1 Energy.",
  social: "💓 Social matching, message boards and personality-based discovery. Filter creators by NationalitieZ heritage to find your people.",
  profilez: "🎭 Your public identity — pick every PersonaZ you play, set ZodiacZ from your birthday, and choose the NationalitieZ that represent your ancestry.",
  specz: "⭐ User metadata & UGC you attach to any app. A StatZ perk: buy SpecZ with SpinaZ to tune how your apps read you.",
  membershipz: "💳 MembershipZ — upgrade your tier for lower platform fees, more Energy per top-up, more daily AI prompts, and the StatZ-only SpecZ marketplace. Founding members lock in 50% off for life.",
  adz: "📺 AdZ — watch a short rewarded ad and earn SpinaZ. Ads play in the mobile app via AdMob; your reward lands automatically when the ad finishes.",
  offerz: "🎁 OfferZ — complete offers (surveys, sign-ups, installs) on the offerwall and earn SpinaZ, credited automatically once the provider confirms.",
  mimez: "🤫 MimeZ — silent-performance training and practice drills.",
  directz: "🎬 DirectZ — directing tools and guided sessions.",
  lessonz: "📚 LessonZ — book and run lessons; teachers set skills, rates and availability.",
  singz: "🎤 SingZ — vocal training: range detection, quests, Boss SongZ — voice health first.",
  rapz: "🎤 RapZ — rap training: style tracks, breath control, combo meter, Boss Mode.",
  messagez: "📨 MessageZ — your messaging center: Inbox and Outbox.",
  journalz: "📔 JournalZ — your diary. A day, written down: mood, weather, tags, the people you were with and where you were. Every entry is private until you publish it — tagging somebody on a private entry tells them nothing. Your first entry each day completes a QuestZ daily.",
  collabz: "🤝 CollabZ — collaborate and manage projects: OriginalZ, CoverZ, RemixeZ.",
  battlez: "🪖 BattleZ — one post versus another. Verified 18+ can bet on themselves; others bet SpinaZ.",
  labelz: "🏷️ LabelZ — public groups with record-label logic: advances, terms, e-signed contracts (Premium / A&R Scout / Manager).",
  groupz: "👥 GroupZ — combine users into editable groups: Friends, Fans, Partners, Blocked, Custom.",
  bugz: "🐞 BugZ — submit a bug as a post. Admins mark it In Progress or Squashed (Squashed rewards 200 SpinaZ).",
  funnelz: "📊 FunnelZ — owner-only. The join funnel measured: landing → trial → register, real events and real unique visitors.",
};

function Home() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  // Read the slug off the path rather than from useParams: the tab routes are
  // listed explicitly (so an unknown address still redirects) and an explicit
  // path has no params to read.
  const slug = useLocation().pathname.replace(/^\/+|\/+$/g, "");
  const [tab, setTab] = useState(null); // decided from the URL or onboarded state
  const [infoKey, setInfoKey] = useState(null);
  // LogicZ: what each tab is and what lives inside it, from the server, so the
  // description a member reads can't drift from the thing they land on.
  const [logicz, setLogicz] = useState({});
  const [memberKey, setMemberKey] = useState(null); // username whose profile is open
  const [tourMe, setTourMe] = useState(null); // account state the tour gates on
  const refreshTourMe = useCallback(() => {
    api("/api/auth/me/").then(setTourMe).catch(() => {});
  }, []);
  const idx = Math.max(0, TABS.findIndex((t) => t.key === tab));
  const active = TABS[idx];
  const infoTab = infoKey ? TABS.find((t) => t.key === infoKey) : null;
  const logic = infoTab ? logicz[infoTab.key] : null;
  const today = new Date().toLocaleDateString();
  // PickConnectZ dock — pinned apps + the ones this member opens most.
  const { usage, pins, togglePin } = usePickConnectZ(tab);
  // FunnelZ is owner-only real visitor data — not something to advertise in
  // the drawer for everyone. The route and TABS entry still exist (so the
  // info modal, ⓘ, and a direct link work for the owner); this only trims
  // what the Dock lists.
  const dockApps = user?.is_owner ? TABS : TABS.filter((t) => t.key !== "funnelz");

  // One way in and out of a tab: set the state AND the address, together. Two
  // paths would let the URL say one thing while the screen showed another.
  const openTab = (key) => {
    setTab(key);
    navigate(`/${slugFor(key)}`, { replace: false });
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const go = (delta) => {
    const n = (idx + delta + TABS.length) % TABS.length;
    openTab(TABS[n].key);
  };

  // Lets any tab (e.g. OnboardZ steps) jump to another tab.
  useEffect(() => {
    const h = (e) => {
      if (TABS.some((t) => t.key === e.detail)) {
        setTab(e.detail);
        navigate(`/${slugFor(e.detail)}`);
        window.scrollTo({ top: 0, behavior: "smooth" });
      }
    };
    window.addEventListener("mcz-goto-tab", h);
    return () => window.removeEventListener("mcz-goto-tab", h);
  }, [navigate]);

  useEffect(() => {
    api("/api/economy/logicz/")
      .then((d) => setLogicz(Object.fromEntries(asList(d?.tabs).map((t) => [t.key, t]))))
      .catch(() => {});   // the modal falls back to its built-in copy
  }, []);

  // The address decides the tab, so a pasted link, a bookmark and the back
  // button all land in the same place.
  useEffect(() => {
    const t = tabForSlug(slug);
    if (t && t.key !== tab) setTab(t.key);
  }, [slug]);

  // New users land on OnboardZ until they've completed it; returning users on PostZ.
  // A checkout return (?checkout=…) lands on MembershipZ so the result is shown.
  useEffect(() => {
    // An address wins over the default landing — someone opening /battle asked
    // for BattleZ, not for wherever we would have sent them.
    if (tabForSlug(slug)) return;
    if (new URLSearchParams(window.location.search).has("checkout")) {
      setTab("membershipz");
      return;
    }
    api("/api/auth/me/")
      .then((m) => setTab(m?.onboarded ? "postz" : "onboardz"))
      .catch(() => setTab("postz"));
  }, []);

  // Gate AFTER the hooks above, never before them. `tab` starts null, so an
  // early return here used to skip both useEffect calls on the very first
  // render — including the one that picks the tab — leaving nothing to ever
  // call setTab. The app sat on this spinner forever, with no request made
  // and nothing logged to the console.
  if (!tab) {
    return (
      <div className="flex min-h-screen items-center justify-center text-white/50">
        <Loader2 className="mr-2 animate-spin" size={18} /> Loading…
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      {/* Sticky header */}
      <header className="sticky top-0 z-50 border-b border-white/10 bg-mcz-bg/80 backdrop-blur">
        <div
          className="mx-auto flex max-w-4xl items-center gap-3 px-4 py-3"
          style={{ boxShadow: "0 1px 0 rgba(168,85,247,0.15)" }}
        >
          <div className="flex items-center gap-1">
            <a {...openable(`/${slugFor(TABS[(idx - 1 + TABS.length) % TABS.length].key)}`, () => go(-1))}
               className="rounded-lg p-1.5 text-white/60 hover:bg-white/10" title="Previous tab">
              <ChevronLeft size={18} />
            </a>
            <a {...openable(`/${slugFor(TABS[(idx + 1) % TABS.length].key)}`, () => go(1))}
               className="rounded-lg p-1.5 text-white/60 hover:bg-white/10" title="Next tab">
              <ChevronRight size={18} />
            </a>
          </div>

          <a {...openable("/post", () => openTab("postz"))} className="flex items-center gap-2"
             title="PostZ — ctrl/cmd-click for a new tab">
            <img src="/mcz-logo-v5.jpg" alt="Music ConnectZ" className="h-10 w-10 rounded-xl shadow-neon" />
            <span className="hidden font-display text-lg font-extrabold tracking-tight sm:inline">
              Music ConnectZ
            </span>
          </a>

          {/* LogicZ: the tab's own icon, and clicking it opens the modal that
              says what this tab is. The control used to be text with a ⓘ — the
              icon is the thing the spec points at, and the thing a member's
              thumb actually finds. */}
          <button data-tour="tab-info" className="flex flex-1 items-center justify-center gap-2"
                  onClick={() => setInfoKey(tab)} title="What is this tab?">
            {active?.icon && (
              <IconImg icon={active.icon} alt="" className="h-7 w-7 shrink-0 rounded-lg" />
            )}
            <span className="min-w-0 text-center">
              <span className="block text-[11px] font-semibold text-white/70">
                {active?.label} <span className="text-white/30">ⓘ</span>
              </span>
              <span className="block text-[9px] text-white/35">{today}</span>
            </span>
          </button>

          <a
            {...openable("/profile", () => openTab("profilez"))}
            className="flex items-center gap-1 rounded-full border border-white/10 bg-white/5 px-2 py-1 hover:bg-white/10"
            title="ProfileZ — ctrl/cmd-click for a new tab"
          >
            <IconImg icon="personaz.png" alt="" className="h-7 w-7 rounded-full object-cover" />
          </a>
          <SoundToggle />
          <button onClick={logout} className="rounded-lg p-1.5 text-white/60 hover:bg-white/10" title="Log out">
            <LogOut size={16} />
          </button>
        </div>

        {/* No tab bar: PickConnectZ at the foot of the screen is the primary
            nav. Its ⊞ drawer lists every app, so nothing is unreachable. */}
      </header>

      {/* pb leaves room for the fixed PickConnectZ dock */}
      <main className="mx-auto max-w-4xl px-4 pb-40 pt-5">
        <p className="mb-4 text-xs text-white/45">
          Signed in as <span className="text-white/80">{user?.username}</span>
        </p>
        <CommunityBar onOpenMember={setMemberKey} />
        {/* keyed by tab so switching apps clears a previous app's crash */}
        <ErrorBoundary key={tab} label={active?.label}>
          <Suspense fallback={<RouteFallback />}>{active?.el}</Suspense>
        </ErrorBoundary>
      </main>

      {/* Tab description modal — opened by clicking the active tab / its icon. */}
      {infoTab && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"
          onClick={() => setInfoKey(null)}
        >
          <div
            className="neon-frame w-full max-w-md p-5"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-3 flex items-center gap-3">
              <IconImg icon={infoTab.icon} alt="" className="h-14 w-14 rounded-2xl shadow-neon" />
              <h3 className="font-display text-2xl font-extrabold">{infoTab.label}</h3>
            </div>
            <p className="text-sm leading-relaxed text-white/75">
              {logic?.desc || TAB_ABOUT[infoTab.key] || "A Music ConnectZ app."}
            </p>

            {/* Its address. The whole point of LogicZ — this is the thing you
                paste to somebody. */}
            <p className="mt-3 font-mono text-[11px] text-mcz-cyan">
              musicconnectz.net/{slugFor(infoTab.key)}
            </p>

            {/* What lives in this tab, and honestly whether it exists yet. A
                modal promising five apps and delivering one is worse than one
                promising one. */}
            {logic?.apps?.length > 0 && (
              <ul className="mt-3 space-y-1.5 border-t border-white/[0.08] pt-3">
                {logic.apps.map((a) => (
                  <li key={a.name} className="flex items-start gap-2 text-[12px]">
                    <span className="shrink-0">{a.emoji}</span>
                    <span className="min-w-0">
                      <span className={a.built ? "text-white/80" : "text-white/40"}>
                        {a.name}
                      </span>
                      {!a.built && (
                        <span className="ml-1 text-[10px] text-mcz-gold">not built yet</span>
                      )}
                      <span className="block text-[11px] leading-relaxed text-white/40">
                        {a.desc}
                      </span>
                    </span>
                  </li>
                ))}
              </ul>
            )}

            <button className="re-btn mt-5" onClick={() => setInfoKey(null)}>Got it</button>
          </div>
        </div>
      )}

      {memberKey && (
        <Suspense fallback={null}>
          <MemberProfile username={memberKey} onClose={() => setMemberKey(null)} />
        </Suspense>
      )}

      <Tour me={tourMe} onRefreshMe={refreshTourMe} />

      {/* Above the dock, so it sits at the foot of the page without fighting
          the fixed navigation. AdFrame renders nothing AT ALL unless the server
          says this member may see a third-party ad — including its own spacing,
          which is why there is no wrapper here. A wrapper would survive the
          null and leave a teen looking at a padded gap where an advert isn't. */}
      <AdFrame site="ZACU2vY1f3nZNiZ6QTNJ" />

      <Dock
        apps={dockApps}
        usage={usage}
        pins={pins}
        tier={user?.tier}
        current={tab}
        onOpen={openTab}
        onTogglePin={togglePin}
      />
    </div>
  );
}

function OAuthCallback() {
  const { oauth } = useAuth();
  const navigate = useNavigate();
  const [error, setError] = useState("");

  const ran = useRef(false);

  useEffect(() => {
    if (ran.current) return; // StrictMode double-invokes; the values below are single-use
    ran.current = true;

    const params = new URLSearchParams(window.location.search);
    const code = params.get("code");
    const returnedState = params.get("state");

    // Read then immediately clear: each of these belongs to exactly one
    // sign-in attempt and must not be reusable by the next request.
    const provider = sessionStorage.getItem("mcz_oauth_provider");
    const expectedState = sessionStorage.getItem("mcz_oauth_state");
    const verifier = sessionStorage.getItem("mcz_oauth_verifier");
    sessionStorage.removeItem("mcz_oauth_provider");
    sessionStorage.removeItem("mcz_oauth_state");
    sessionStorage.removeItem("mcz_oauth_verifier");

    const denied = params.get("error_description") || params.get("error");
    if (denied) {
      setError(denied);
      return;
    }
    if (!code) {
      navigate("/login", { replace: true });
      return;
    }
    // The state check is what stops someone handing you a link that finishes
    // THEIR sign-in in YOUR browser. It was generated and stored in start(),
    // but nothing verified it came back, which left the flow open to CSRF.
    // A missing provider means this tab never began a sign-in at all — don't
    // guess one, or a stray code gets replayed against the wrong provider.
    if (!provider || !expectedState) {
      setError("This sign-in didn't start in this tab. Please try again from the login screen.");
      return;
    }
    if (returnedState !== expectedState) {
      setError("Sign-in couldn't be verified. Please start again from the login screen.");
      return;
    }

    const redirect =
      import.meta.env.VITE_OAUTH_REDIRECT || `${window.location.origin}/oauth/callback`;
    const body = { code, redirect_uri: redirect };
    if (verifier) body.code_verifier = verifier;
    oauth(provider, body)
      .then(() => navigate("/", { replace: true }))
      .catch((e) => setError(e.message));
  }, [oauth, navigate]);

  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-3 text-white/60">
      {error ? (
        <>
          <p className="text-mcz-pink">{error}</p>
          <button className="neon-btn-ghost !w-auto px-4 py-2" onClick={() => navigate("/login")}>
            Back to login
          </button>
        </>
      ) : (
        <>
          <Loader2 className="animate-spin" size={20} /> Finishing sign-in…
        </>
      )}
    </div>
  );
}

export default function App() {
  return (
    <Suspense fallback={<RouteFallback />}>
    <Routes>
      <Route path="/login" element={<Login />} />
      <Route path="/register" element={<Register />} />
      <Route path="/forgot" element={<ForgotPassword />} />
      <Route path="/reset-password" element={<ResetPassword />} />
      <Route path="/oauth/callback" element={<OAuthCallback />} />
      {/* Public — readable with no account. By link, never by browse: there is
          no anonymous feed and no anonymous member search. */}
      <Route path="/p/:id" element={<PublicPost />} />
      <Route path="/u/:username" element={<PublicProfile />} />
      <Route path="/try" element={<TrialTake />} />
      <Route path="/try/:appKey" element={<TrialTake />} />
      <Route path="/pl/:id" element={<PublicPlaylist />} />
      <Route path="/" element={<RootRoute />} />
      {/* LogicZ: one address per tab. Listed explicitly rather than as a
          catch-all so an unknown path still falls through to the redirect
          below instead of rendering an app shell with no tab in it. */}
      {TABS.map((t) => (
        <Route
          key={t.key}
          path={`/${slugFor(t.key)}`}
          element={
            <RequireAuth>
              <Home />
            </RequireAuth>
          }
        />
      ))}
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
    </Suspense>
  );
}
