// GENERATED by tools/build-icon-manifest.mjs — do not edit. Change
// tools/supplied-icons.txt or the maps in that script, then rebuild:
//
//     node tools/build-icon-manifest.mjs
//
// src/iconManifest.test.mjs fails when this file is stale, so a new file in
// public/icons cannot sit unnoticed.

// Registry key -> the custom artwork Corey supplied for it. ONLY files that are
// committed appear here, so nothing points at a 404. `IconImg` tries this
// first and falls back to CUSTOM_ICONS, so custom art always wins and the
// generated glyphs are the backup, never the reverse.
export const ICON_DEFAULTS = {
  "battlez.1v1.png": "/icons/battlez.1v1.png",
  "battlez.cypher.jpg": "/icons/battlez.cypher.jpg",
  "battlez.freestyle.png": "/icons/battlez.freestyle.png",
  "battlez.png": "/icons/battlez.png",
  "bodiez.png": "/icons/bodiez.png",
  "bugz.png": "/icons/bugz.png",
  "builder.png": "/icons/builder.png",
  "coachz.jpg": "/icons/coachz.jpg",
  "collabz.coverz.png": "/icons/collabz.coverz.png",
  "collabz.originalz.png": "/icons/collabz.originalz.png",
  "collabz.png": "/icons/collabz.png",
  "collabz.remixez.png": "/icons/collabz.remixez.png",
  "distributez.png": "/icons/distributez.png",
  "gamez.png": "/icons/gamez.png",
  "gitz.png": "/icons/gitz.png",
  "groupz.png": "/icons/groupz.png",
  "tellz.png": "/icons/tellz.png",
  "labelz.png": "/icons/labelz.png",
  "lilithz.png": "/icons/lilith.png",
  "logz.png": "/icons/logz.png",
  "messagez.png": "/icons/messagez.png",
  "nationalitiez.png": "/icons/nationalitiez.png",
  "rapz.png": "/icons/rapz.png",
  "singz.png": "/icons/singz.png",
  "substancez.png": "/icons/substancez.png",
  "toolz.png": "/icons/toolz.png",
  "skillz.png": "/icons/skillz.png",
  "directz.png": "/icons/directz.png"
};

// BodieZ muscle group -> supplied art, for the picker that reads it directly.
export const MUSCLE_ART = {};

// Parents and their children, by filename: `battlez.png` is a parent and
// `battlez.cypher.png` its child. `art` is null while the file is not committed.
export const ICON_TREE = [
  {
    "parent": "analyticsz",
    "label": "AnalyticsZ",
    "root": {
      "file": "analyticsz.png",
      "art": null,
      "key": "analytics.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "battlez",
    "label": "BattleZ",
    "root": {
      "file": "battlez.png",
      "art": "/icons/battlez.png",
      "key": "battlez.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": [
      {
        "child": "1v1",
        "label": "1v1",
        "file": "battlez.1v1.png",
        "art": "/icons/battlez.1v1.png",
        "key": "battlez.1v1.png",
        "status": "live",
        "note": "replaces the generated glyph /icons/battlez.1v1-neon.svg",
        "also": []
      },
      {
        "child": "cypher",
        "label": "Cypher",
        "file": "battlez.cypher.jpg",
        "art": "/icons/battlez.cypher.jpg",
        "key": "battlez.cypher.jpg",
        "status": "live",
        "note": "on disk as \"Battlez.cypher.jpg\"; commit it as battlez.cypher.jpg; replaces the generated glyph /icons/battlez.cypher-neon.svg",
        "also": [
          {
            "file": "battlez.cypher.png",
            "status": "owed",
            "note": "the registry keys both battlez.cypher.png and .jpg; only the .jpg is committed"
          }
        ]
      },
      {
        "child": "freestyle",
        "label": "Freestyle",
        "file": "battlez.freestyle.png",
        "art": "/icons/battlez.freestyle.png",
        "key": "battlez.freestyle.png",
        "status": "live",
        "note": "replaces the generated glyph /icons/battlez.freestyle-neon.svg",
        "also": []
      }
    ]
  },
  {
    "parent": "boardz",
    "label": "BoardZ",
    "root": {
      "file": "boardz.jpg",
      "art": null,
      "key": "boardz.png",
      "status": "owed",
      "note": "on disk as \"BoardZ.jpg\"; commit it as boardz.jpg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "bodiez",
    "label": "BodieZ",
    "root": {
      "file": "bodiez.png",
      "art": "/icons/bodiez.png",
      "key": "bodiez.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": [
      {
        "child": "absz",
        "label": "AbsZ",
        "file": "bodiez.absz.svg",
        "art": "/icons/bodiez.absz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": []
      },
      {
        "child": "abz",
        "label": "AbZ",
        "file": "bodiez.abz.jpg",
        "art": null,
        "key": null,
        "status": "owed",
        "note": "BodieZ muscle picker",
        "also": []
      },
      {
        "child": "backz",
        "label": "BackZ",
        "file": "bodiez.backz.svg",
        "art": "/icons/bodiez.backz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.backz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "bicepz",
        "label": "BicepZ",
        "file": "bodiez.bicepz.svg",
        "art": "/icons/bodiez.bicepz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.bicepz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "cardioz",
        "label": "CardioZ",
        "file": "bodiez.cardioz.svg",
        "art": "/icons/bodiez.cardioz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": []
      },
      {
        "child": "chestz",
        "label": "ChestZ",
        "file": "bodiez.chestz.svg",
        "art": "/icons/bodiez.chestz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.chestz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "forearmz",
        "label": "ForearmZ",
        "file": "bodiez.forearmz.svg",
        "art": "/icons/bodiez.forearmz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.forearmz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "fullbodyz",
        "label": "Full BodyZ",
        "file": "bodiez.fullbodyz.svg",
        "art": "/icons/bodiez.fullbodyz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": []
      },
      {
        "child": "glutez",
        "label": "GluteZ",
        "file": "bodiez.glutez.svg",
        "art": "/icons/bodiez.glutez.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.glutez.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "lowerlegz",
        "label": "LowerlegZ",
        "file": "bodiez.lowerlegz.svg",
        "art": "/icons/bodiez.lowerlegz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.lowerlegz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "old",
        "label": "Old",
        "file": "bodiez-old.jpg",
        "art": null,
        "key": null,
        "status": "unplaced",
        "note": "",
        "also": []
      },
      {
        "child": "shoulderz",
        "label": "ShoulderZ",
        "file": "bodiez.shoulderz.svg",
        "art": "/icons/bodiez.shoulderz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.shoulderz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "totalbody",
        "label": "Total Body",
        "file": "bodiez.totalbody.jpg",
        "art": null,
        "key": null,
        "status": "owed",
        "note": "BodieZ muscle picker",
        "also": []
      },
      {
        "child": "tricepz",
        "label": "TricepZ",
        "file": "bodiez.tricepz.svg",
        "art": "/icons/bodiez.tricepz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.tricepz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "upperlegz",
        "label": "UpperlegZ",
        "file": "bodiez.upperlegz.svg",
        "art": "/icons/bodiez.upperlegz.svg",
        "key": null,
        "status": "fallback",
        "note": "the BodieZ muscle picker's current art, kept as the fallback",
        "also": [
          {
            "file": "bodiez.upperlegz.jpg",
            "status": "owed",
            "note": "BodieZ muscle picker"
          }
        ]
      },
      {
        "child": "uppper-legz",
        "label": "Uppper-legZ",
        "file": "bodiez.uppper-legz.jpg",
        "art": null,
        "key": null,
        "status": "duplicate",
        "note": "same icon as bodiez.upperlegz.jpg (typo: three p's)",
        "also": []
      }
    ]
  },
  {
    "parent": "bugz",
    "label": "BugZ",
    "root": {
      "file": "bugz.png",
      "art": "/icons/bugz.png",
      "key": "bugz.png",
      "status": "live",
      "note": "replaces the generated glyph /icons/bugz-neon.svg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "builder",
    "label": "Builder",
    "root": {
      "file": "builder.png",
      "art": "/icons/builder.png",
      "key": "builder.png",
      "status": "live",
      "note": ""
    },
    "extra": [
      {
        "file": "builder.jpg",
        "status": "duplicate",
        "note": "same icon as builder.png; on disk as \"Builder.jpg\"; commit it as builder.jpg"
      }
    ],
    "children": []
  },
  {
    "parent": "callz",
    "label": "CallZ",
    "root": null,
    "extra": [],
    "children": [
      {
        "child": "ai",
        "label": "AI",
        "file": "callz.ai.png",
        "art": null,
        "key": "callz_ai.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "user",
        "label": "User",
        "file": "callz.user.png",
        "art": null,
        "key": "callz_user.png",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "chordz",
    "label": "ChordZ",
    "root": {
      "file": "chordz.jpg",
      "art": null,
      "key": "chordz.jpg",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "coachz",
    "label": "CoachZ",
    "root": {
      "file": "coachz.jpg",
      "art": "/icons/coachz.jpg",
      "key": "coachz.jpg",
      "status": "live",
      "note": "on disk as \"CoachZ.jpg\"; commit it as coachz.jpg; replaces the generated glyph /icons/coachz-neon.svg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "collabz",
    "label": "CollabZ",
    "root": {
      "file": "collabz.png",
      "art": "/icons/collabz.png",
      "key": "collabz.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": [
      {
        "child": "coverz",
        "label": "CoverZ",
        "file": "collabz.coverz.png",
        "art": "/icons/collabz.coverz.png",
        "key": "collabz.coverz.png",
        "status": "live",
        "note": "",
        "also": []
      },
      {
        "child": "originalz",
        "label": "OriginalZ",
        "file": "collabz.originalz.png",
        "art": "/icons/collabz.originalz.png",
        "key": "collabz.originalz.png",
        "status": "live",
        "note": "on disk as \"Collabz.originalz.png\"; commit it as collabz.originalz.png; replaces the generated glyph /icons/collabz.originalz-neon.svg",
        "also": []
      },
      {
        "child": "remixez",
        "label": "RemixeZ",
        "file": "collabz.remixez.png",
        "art": "/icons/collabz.remixez.png",
        "key": "collabz.remixez.png",
        "status": "live",
        "note": "replaces the generated glyph /icons/collabz.remixez-neon.svg",
        "also": []
      }
    ]
  },
  {
    "parent": "crewz",
    "label": "CrewZ",
    "root": {
      "file": "crewz.jpg",
      "art": null,
      "key": "crewz.png",
      "status": "owed",
      "note": "on disk as \"Crewz icon.jpg\"; commit it as crewz.jpg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "dawz",
    "label": "DawZ",
    "root": {
      "file": "dawz.jpg",
      "art": null,
      "key": "dawz.png",
      "status": "owed",
      "note": "on disk as \"Dawz.jpg\"; commit it as dawz.jpg"
    },
    "extra": [],
    "children": [
      {
        "child": "arsenal",
        "label": "Arsenal",
        "file": "dawz.arsenal.jpg",
        "art": null,
        "key": "arsenal.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "azrael",
        "label": "Azrael",
        "file": "dawz.azrael.png",
        "art": null,
        "key": "azrael.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "formulawon",
        "label": "FormulaWon",
        "file": "dawz.formulawon.jpg",
        "art": null,
        "key": "dawz_formulawon.png",
        "status": "owed",
        "note": "on disk as \"Dawz.FormulaWon.jpg\"; commit it as dawz.formulawon.jpg",
        "also": []
      },
      {
        "child": "fruity",
        "label": "Fruity Möbius",
        "file": "dawz.fruity.png",
        "art": null,
        "key": "fruity_mobius.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "intuitionz",
        "label": "IntuitionZ",
        "file": "dawz.intuitionz.jpg",
        "art": null,
        "key": "intuition.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "trump",
        "label": "Trump Toupee",
        "file": "dawz.trump.png",
        "art": null,
        "key": "trump_toupee.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "witch",
        "label": "Witchcraft",
        "file": "dawz.witch.png",
        "art": null,
        "key": "witchcraft.png",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "distributez",
    "label": "DistributeZ",
    "root": {
      "file": "distributez.png",
      "art": "/icons/distributez.png",
      "key": "distributez.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "drumz",
    "label": "DrumZ",
    "root": {
      "file": "drumz.jpg",
      "art": null,
      "key": "drumz.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "fanz",
    "label": "FanZ",
    "root": {
      "file": "fanz.jpg",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "no key or tab; the GroupZ Fanz child is groupz.fanz.jpg — likely the same art"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "filez",
    "label": "FileZ",
    "root": {
      "file": "filez.jpg",
      "art": null,
      "key": "filez.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "friends",
    "label": "Friends",
    "root": {
      "file": "friends.png",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "no key or tab; sits beside friendz.jpg — two friend icons and one place for them"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "friendz",
    "label": "FriendZ",
    "root": {
      "file": "friendz.jpg",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "no key or tab; the GroupZ Friendz child is groupz.friendz.jpg — likely the same art"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "gamez",
    "label": "GameZ",
    "root": {
      "file": "gamez.png",
      "art": "/icons/gamez.png",
      "key": "gamez.png",
      "status": "live",
      "note": "on disk as \"Gamez.png\"; commit it as gamez.png"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "gitz",
    "label": "GitZ",
    "root": {
      "file": "gitz.png",
      "art": "/icons/gitz.png",
      "key": "gitz.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "groupz",
    "label": "GroupZ",
    "root": {
      "file": "groupz.png",
      "art": "/icons/groupz.png",
      "key": "groupz.png",
      "status": "live",
      "note": "replaces the generated glyph /icons/groupz-neon.svg"
    },
    "extra": [],
    "children": [
      {
        "child": "blocked",
        "label": "Blocked",
        "file": "groupz.blocked.png",
        "art": null,
        "key": "groupz_blocked.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "custom",
        "label": "Custom",
        "file": "groupz.custom.png",
        "art": null,
        "key": "groupz_custom.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "fanz",
        "label": "FanZ",
        "file": "groupz.fanz.jpg",
        "art": null,
        "key": "groupz_fanz.png",
        "status": "owed",
        "note": "on disk as \"groupz..fanz.jpg\"; commit it as groupz.fanz.jpg",
        "also": []
      },
      {
        "child": "friendz",
        "label": "FriendZ",
        "file": "groupz.friendz.jpg",
        "art": null,
        "key": "groupz_friendz.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "partnerz",
        "label": "PartnerZ",
        "file": "groupz.partnerz.jpg",
        "art": null,
        "key": "partnerz.jpg",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "home",
    "label": "Home",
    "root": {
      "file": "home.jpg",
      "art": null,
      "key": "homez.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "intelligence",
    "label": "Intelligence",
    "root": {
      "file": "intelligencez.png",
      "art": null,
      "key": "intelligencez.png",
      "status": "owed",
      "note": "on disk as \"Intelligencez.png\"; commit it as intelligencez.png"
    },
    "extra": [],
    "children": [
      {
        "child": "imageconz",
        "label": "Image ConnectZ",
        "file": "intelligence.imageconz.png",
        "art": null,
        "key": "imageconnectz.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "instconz",
        "label": "Instrumental ConnectZ",
        "file": "intelligence.instconz.jpg",
        "art": null,
        "key": "instrumentalconnectz.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "ocular",
        "label": "Ocular Code ConnectZ",
        "file": "intelligence.ocular.png",
        "art": null,
        "key": "occ.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "sentenceconz",
        "label": "Sentence ConnectZ",
        "file": "intelligence.sentenceconz.png",
        "art": null,
        "key": "sentencez.png",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "karmaz",
    "label": "KarmaZ",
    "root": {
      "file": "karmaz.jpg",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "no KarmaZ tab, app or registry key exists yet; also on disk as \"karmaz (2).jpg\" — a copy"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "labelz",
    "label": "LabelZ",
    "root": {
      "file": "labelz.png",
      "art": "/icons/labelz.png",
      "key": "labelz.png",
      "status": "live",
      "note": "replaces the generated glyph /icons/labelz-neon.svg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "languagez",
    "label": "LanguageZ",
    "root": {
      "file": "languagez.jpg",
      "art": null,
      "key": "languagez.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "lilith",
    "label": "Lilith",
    "root": {
      "file": "lilith.png",
      "art": "/icons/lilith.png",
      "key": "lilithz.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": [
      {
        "child": "routinez",
        "label": "RoutineZ",
        "file": "lilith.routinez.jpg",
        "art": null,
        "key": null,
        "status": "unplaced",
        "note": "no Lilith Routines tab or key; HabitZ (habitz.png) is the nearest surface",
        "also": []
      },
      {
        "child": "someday",
        "label": "Someday",
        "file": "lilith.someday.png",
        "art": null,
        "key": "lilith_someday.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "taskz",
        "label": "TaskZ",
        "file": "lilith.taskz.webp",
        "art": "/icons/lilith.taskz.webp",
        "key": null,
        "status": "fallback",
        "note": "current art for registry key lilithz.png, kept as the fallback",
        "also": [
          {
            "file": "lilith.taskz.jpg",
            "status": "owed",
            "note": ""
          }
        ]
      },
      {
        "child": "today",
        "label": "Today",
        "file": "lilith.today.png",
        "art": null,
        "key": "lilith_today.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "upcoming",
        "label": "Upcoming",
        "file": "lilith.upcoming.png",
        "art": null,
        "key": "lilith_upcoming.png",
        "status": "owed",
        "note": "on disk as \"ImgResizer_lilith.upcoming (1).png\"; commit it as lilith.upcoming.png",
        "also": []
      }
    ]
  },
  {
    "parent": "logo",
    "label": "Logo",
    "root": {
      "file": "logo.jpg",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "the logo is registered as logo.png -> /mcz-logo-v5.jpg at the site root"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "logz",
    "label": "LogZ",
    "root": {
      "file": "logz.png",
      "art": "/icons/logz.png",
      "key": "logz.png",
      "status": "live",
      "note": "on disk as \"LogZ.png\"; commit it as logz.png; replaces the generated glyph /icons/logz-neon.svg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "mcz-logo-v5",
    "label": "Mcz-logo-v5",
    "root": {
      "file": "mcz-logo-v5.jpg",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "the same logo is already served from the site root (/mcz-logo-v5.jpg)"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "messagez",
    "label": "MessageZ",
    "root": {
      "file": "messagez.png",
      "art": "/icons/messagez.png",
      "key": "messagez.png",
      "status": "live",
      "note": "replaces the generated glyph /icons/messagez-neon.svg"
    },
    "extra": [],
    "children": [
      {
        "child": "inbox",
        "label": "Inbox",
        "file": "messagez.inbox.png",
        "art": null,
        "key": "inbox.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "outbox",
        "label": "Outbox",
        "file": "messagez.outbox.jpg",
        "art": null,
        "key": "messagez_outbox.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "parcel",
        "label": "Parcel",
        "file": "messagez.parcel.png",
        "art": null,
        "key": "parcel.png",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "nationalitiez",
    "label": "NationalitieZ",
    "root": {
      "file": "nationalitiez.png",
      "art": "/icons/nationalitiez.png",
      "key": "nationalitiez.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "opportunitiez",
    "label": "OpportunitieZ",
    "root": {
      "file": "opportunitiez.png",
      "art": null,
      "key": "opportunitiez.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "partners",
    "label": "Partners",
    "root": {
      "file": "partners.png",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "no key or tab; the GroupZ Partners child is groupz.partnerz.jpg — likely the same art"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "personaz",
    "label": "PersonaZ",
    "root": {
      "file": "personaz.jpg",
      "art": null,
      "key": "personaz.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": [
      {
        "child": "actor",
        "label": "Actor",
        "file": "personaz.actor.jpg",
        "art": null,
        "key": null,
        "status": "unplaced",
        "note": "Actor is not one of the 11 PersonaZ in personas.py or the registry",
        "also": []
      },
      {
        "child": "actress",
        "label": "Actress",
        "file": "personaz.actress.jpg",
        "art": null,
        "key": null,
        "status": "unplaced",
        "note": "Actress is not one of the 11 PersonaZ in personas.py or the registry",
        "also": []
      },
      {
        "child": "coach",
        "label": "Coach",
        "file": "personaz.coach.jpg",
        "art": null,
        "key": "personaz_coach.jpg",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "developer",
        "label": "Developer",
        "file": "personaz.developer.png",
        "art": null,
        "key": "personaz_developer.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "manager",
        "label": "Manager",
        "file": "personaz.manager.png",
        "art": null,
        "key": "personaz_manager.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "mixengineer",
        "label": "Mix Engineer",
        "file": "personaz.mixengineer.png",
        "art": null,
        "key": "personaz_mixengineer.png",
        "status": "owed",
        "note": "on disk as \"personaz.mix engineer.png\"; commit it as personaz.mixengineer.png",
        "also": []
      },
      {
        "child": "videographer",
        "label": "Videographer",
        "file": "personaz.videographer.png",
        "art": null,
        "key": "personaz_videographer.png",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "pivkconnectz",
    "label": "PivkconnectZ",
    "root": {
      "file": "pivkconnectz.png",
      "art": null,
      "key": "pickconz.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "profilez",
    "label": "ProfileZ",
    "root": {
      "file": "profilez.png",
      "art": null,
      "key": "profilez.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": [
      {
        "child": "preferencez",
        "label": "PreferenceZ",
        "file": "profilez.preferencez.png",
        "art": null,
        "key": "preferencez.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "religionz",
        "label": "ReligionZ",
        "file": "profilez.religionz.jpg",
        "art": null,
        "key": null,
        "status": "unplaced",
        "note": "ProfileZ has a religion field but no icon slot for it",
        "also": []
      }
    ]
  },
  {
    "parent": "rapz",
    "label": "RapZ",
    "root": {
      "file": "rapz.png",
      "art": "/icons/rapz.png",
      "key": "rapz.png",
      "status": "live",
      "note": "replaces the generated glyph /icons/rapz-neon.svg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "recordingz",
    "label": "RecordingZ",
    "root": {
      "file": "recordingz.jpg",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "no RecordingZ tab, app or registry key exists yet"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "singz",
    "label": "SingZ",
    "root": {
      "file": "singz.png",
      "art": "/icons/singz.png",
      "key": "singz.png",
      "status": "live",
      "note": "replaces the generated glyph /icons/singz-neon.svg"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "socializez",
    "label": "SocialiZeZ",
    "root": {
      "file": "socializez.jpg",
      "art": null,
      "key": "social_connectz.png",
      "status": "owed",
      "note": ""
    },
    "extra": [],
    "children": [
      {
        "child": "infernoz",
        "label": "InfernoZ",
        "file": "socializez.infernoz.jpg",
        "art": null,
        "key": null,
        "status": "unplaced",
        "note": "InfernoZ is drawn from ToolZMenu.jsx's own map (offerz-neon.svg), not the registry; on disk as \"socializez.infernoZ.jpg\"; commit it as socializez.infernoz.jpg",
        "also": []
      },
      {
        "child": "vybez",
        "label": "VybeZ",
        "file": "socializez.vybez.jpg",
        "art": null,
        "key": "vybez.png",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "statsz",
    "label": "StatsZ",
    "root": {
      "file": "statsz.png",
      "art": null,
      "key": "statsz.png",
      "status": "owed",
      "note": "also on disk as \"statsz - Copy.png\" — a copy"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "stepz-good-bodiez",
    "label": "StepZ Good BodieZ",
    "root": {
      "file": "stepz-good-bodiez.png",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "StepZ is a BodieZ sub-tab that draws no icon; no key exists"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "substancez",
    "label": "SubstanceZ",
    "root": {
      "file": "substancez.png",
      "art": "/icons/substancez.png",
      "key": "substancez.png",
      "status": "live",
      "note": "on disk as \"SubstanceZ.png\"; commit it as substancez.png"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "tellz",
    "label": "TellZ",
    "root": {
      "file": "tellz.png",
      "art": "/icons/tellz.png",
      "key": "tellz.png",
      "status": "live",
      "note": "on disk as \"ImgResizer_Tellz.png\"; commit it as tellz.png"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "toolz",
    "label": "ToolZ",
    "root": {
      "file": "toolz.png",
      "art": "/icons/toolz.png",
      "key": "toolz.png",
      "status": "live",
      "note": "on disk as \"Toolz .png\"; commit it as toolz.png"
    },
    "extra": [
      {
        "file": "toolz.jpg",
        "status": "duplicate",
        "note": "same icon as toolz.png"
      }
    ],
    "children": [
      {
        "child": "cleanconz",
        "label": "Clean ConnectZ",
        "file": "toolz.cleanconz.png",
        "art": null,
        "key": "cleanconnectz.png",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "journalz",
        "label": "JournalZ",
        "file": "toolz.journalz.jpg",
        "art": null,
        "key": "journalz.jpg",
        "status": "owed",
        "note": "",
        "also": []
      },
      {
        "child": "metz",
        "label": "MetZ",
        "file": "toolz.metz.jpg",
        "art": null,
        "key": "metz.jpg",
        "status": "owed",
        "note": "also on disk as \"toolz.metz - Copy.jpg\" — a copy",
        "also": []
      },
      {
        "child": "tunerz",
        "label": "TunerZ",
        "file": "toolz.tunerz.jpg",
        "art": null,
        "key": "tunerz.jpg",
        "status": "owed",
        "note": "",
        "also": []
      }
    ]
  },
  {
    "parent": "tunerz",
    "label": "TunerZ",
    "root": {
      "file": "tunerz.jpg",
      "art": "/icons/tunerz.jpg",
      "key": null,
      "status": "unplaced",
      "note": "the older root art; the tunerz.jpg registry key now belongs to the ToolZ child toolz.tunerz.jpg; also on disk as \"tunerz - Copy.jpg\" — a copy"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "whatineedz",
    "label": "WhatineedZ",
    "root": {
      "file": "whatineedz.png",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "no tab or key — closest is PickConnectZ (pickconz.png), which already has art"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "xp",
    "label": "Xp",
    "root": {
      "file": "xp.jpg",
      "art": null,
      "key": null,
      "status": "unplaced",
      "note": "XP is an emoji resource (⭐ in src/resources.js); no screen draws an icon for it"
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "skillz",
    "label": "SkillZ",
    "root": {
      "file": "skillz.png",
      "art": "/icons/skillz.png",
      "key": "skillz.png",
      "status": "live",
      "note": ""
    },
    "extra": [],
    "children": []
  },
  {
    "parent": "directz",
    "label": "DirectZ",
    "root": {
      "file": "directz.png",
      "art": "/icons/directz.png",
      "key": "directz.png",
      "status": "live",
      "note": "replaces the generated glyph /icons/directz-neon.svg"
    },
    "extra": [],
    "children": []
  }
];

// Icons a tab or app asks for that no supplied file covers.
export const TAB_ICONS_WITHOUT_ART = [
  "adz.png",
  "bassz.png",
  "callz.png",
  "funnelz.png",
  "guitarz.png",
  "habitz.png",
  "keyconnectz.png",
  "keyz.png",
  "lessonz.png",
  "logo.png",
  "mimez.png",
  "money.png",
  "offerz.png",
  "onboardz.png",
  "playlistz.png",
  "postz.png",
  "royaltiez.png",
  "soundcloudengagementz.png",
  "soundz.png",
  "specz.png",
  "venuez.png",
  "violinz.png"
];
